### ISSUE TITLE
No option to display the gradient legend?

### ISSUE THREAD

**Issue by cariacou** [iosphere/Leaflet.hotline#10]
something like that would be very useful:
http://i.stack.imgur.com/EjU61.png

**Comment by klaftertief** [comment]
Hi @cariacou,
the plugin is only focused on drawing the actual polyline.
There is the `getRGBForValue()` method though you can use to get the color as a 3-tuple rgb for a given value to build a legend.
I'm closing this issue for now but I'll keep the suggestion in mind for future features.
