### ISSUE TITLE
Can't use plugin with Mapbox

### ISSUE THREAD

**Issue by brunoaduarte** [iosphere/Leaflet.hotline#2]
When i load 'leaflet.hotline.js' i get an error message:

leaflet.hotline.js:152 Uncaught TypeError: Cannot read property 'extend' of undefined

Line 152 > var Renderer = L.Canvas.extend({ ...

Is there a way to use this great plugin with Mapbox.js ?

**Comment by klaftertief** [comment]
Mapbox.js uses Leaflet 0.7.x. This plugin needs the latest Leaflet 1.0 betas, because the updated API simplifies the code a lot.

I'm sorry to say that we don't have any plans to add support for older Leaflet versions.

There may be a branch of Mapbox.js that supports the latest Leaflet versions.

**Comment by brunoaduarte** [comment]
"Mapbox.js tracks released versions of Leaflet, only. That does not include beta, rc, -dev, or anything else. When there's a Leaflet 1.0, then we'll update. Until then, we will not."

That's sad.

**Comment by klaftertief** [comment]
Leaflet is approaching v 1.0 kind if quickly at the moment. So you might be lucky in a couple of weeks.

**Comment by brunoaduarte** [comment]
Hi again @klaftertief , i've implemented both mapbox.js and leaftlet-v1.0.0-beta.2.js on my project. And i can successfully run the leaflet v1.0 beta2 in one of my controllers using tileLayer: 

```` javascript
// L.version -> 0.7.2
L.noConflict(); // switch to Leaftlet v1.0.0-beta.2
// L.version -> 1.0.0-beta.2			
var map = L.map(mapId).setView([51.505, -0.09], 13);
L.tileLayer(
'http://api.tiles.mapbox.com/v4/' + mapboxId + '/{z}/{x}/{y}.png?access_token=' + mapboxToken,
{ attribution: 'Imagery from <a href="http://mapbox.com/about/maps/">MapBox</a> &mdash; ' + 'Map data {attribution.OpenStreetMap}'
}).addTo(map);
````

but for that i have to call this `L.noConflict();` on my controller so it switches from Leaflet 0.7.2 to 1.0.0-beta2.

Is it possible to do the same inside the hotline plugin ?

I've tried to execute `L.noConflict();` in the beginning of the plugin, but it didn't worked, it didn't switched versions.

```javascript
...
}(this, function (L) {
	
	if(L.version === '0.7.2') {
		L.noConflict();
	}
	
	// Plugin is already added to Leaflet
	if (L.Hotline) {
		return L;
	}
.....
```

Thank you !

**Comment by klaftertief** [comment]
I wouldn't use two different Leaflet versions at the same time. 

If you really want to do it you could assign the beta version to its own namespace via `LeafletBeta =  L.noConflict();` and patch [this line](https://github.com/iosphere/Leaflet.hotline/blob/3b81adcd11a09d8253edfd93891bc2df044c9b46/src/leaflet.hotline.js#L22) to use this global.

**Comment by brunoaduarte** [comment]
It worked, thanks
