### ISSUE TITLE
Display z value on hotline mouseover

### ISSUE THREAD

**Issue by brunoaduarte** [iosphere/Leaflet.hotline#3]
How can i display the z value of a specific point on mouseover ?

**Comment by klaftertief** [comment]
I'm afraid you have to handle this yourself. Leaflets MouseEvents give you the `latlng` where the event occurs, but that is calculated from the mouse position and not from the raw data. So you could either try to find the closest point from your list of points to the `latlng` from the event, or maybe add a Marker/PopUp for each of your points. But this might get expensive. I believe this should live in user space.

**Comment by brunoaduarte** [comment]
Ok, thanks @klaftertief
