### ISSUE TITLE
Hotline layer not removed correctly if outlineColor alpha is 0

### ISSUE THREAD

**Issue by 1z3n** [iosphere/Leaflet.hotline#9]
Hotline layer not removed correctly if `outlineColor` has alpha == 0

so removing outline only works by setting `outlineWidth` to 0, and `outlineColor` with alpha == 1

**Comment by klaftertief** [comment]
Thanks for the report. I'm going to tackle this batched with some other updates in the next couple of days.

**Comment by klaftertief** [comment]
Should be fixed with https://github.com/iosphere/Leaflet.hotline/releases/tag/v0.4.0
